import Footer from "@/components/footer";
import Header from "@/components/header";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const playFair = Playfair_Display({ subsets: ["latin"], variable: "--font-serif" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	// const messages = await getMessages();
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={cn("flex min-h-screen flex-col font-sans antialiased", inter.variable, playFair.variable)}>
				{/* <NextIntlClientProvider messages={messages}> */}
				<Providers>
					<Header />
					<main className="grow">{children}</main>
					<Footer />
				</Providers>
				{/* </NextIntlClientProvider> */}
			</body>
		</html>
	);
}
